import fs from 'fs/promises';
import path from 'path';

const outDir = process.argv[2];
const browserMetaUrl = 'http://127.0.0.1:9222/json/list';
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));
async function fetchJson(url) { const res = await fetch(url); if (!res.ok) throw new Error(`fetch ${url} failed: ${res.status}`); return res.json(); }
async function waitForTarget() { for (let i = 0; i < 60; i++) { try { const list = await fetchJson(browserMetaUrl); const page = list.find((item) => item.type === 'page'); if (page?.webSocketDebuggerUrl) return page.webSocketDebuggerUrl; } catch {} await sleep(250);} throw new Error('No debuggable page target found'); }
class CDP { constructor(ws) { this.ws=ws; this.id=0; this.pending=new Map(); this.events=new Map(); ws.addEventListener('message',(event)=>{ const msg=JSON.parse(event.data); if(msg.id&&this.pending.has(msg.id)){ const {resolve,reject}=this.pending.get(msg.id); this.pending.delete(msg.id); if(msg.error) reject(new Error(msg.error.message)); else resolve(msg.result); return; } const handlers=this.events.get(msg.method)||[]; for(const h of handlers) h(msg.params||{}); }); } on(method,handler){ const arr=this.events.get(method)||[]; arr.push(handler); this.events.set(method,arr);} async send(method,params={}){ const id=++this.id; const payload=JSON.stringify({id,method,params}); const promise=new Promise((resolve,reject)=>this.pending.set(id,{resolve,reject})); this.ws.send(payload); return promise; }}
async function connect(){ const wsUrl=await waitForTarget(); const ws=new WebSocket(wsUrl); await new Promise((resolve,reject)=>{ ws.addEventListener('open',resolve,{once:true}); ws.addEventListener('error',reject,{once:true});}); const cdp=new CDP(ws); await cdp.send('Page.enable'); await cdp.send('Runtime.enable'); await cdp.send('DOM.enable'); await cdp.send('Emulation.setDeviceMetricsOverride',{width:1600,height:1400,deviceScaleFactor:2,mobile:false}); return cdp; }
async function evalValue(cdp,expression){ const result=await cdp.send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true}); return result.result?.value; }
async function captureClip(cdp,name,clip){ const result=await cdp.send('Page.captureScreenshot',{format:'png',clip}); await fs.writeFile(path.join(outDir,`${name}.png`),Buffer.from(result.data,'base64')); }
function paddedClip(rect,pad=44){ return { x: Math.max(0, rect.x-pad), y: Math.max(0, rect.y-pad), width: Math.max(1, rect.width + pad*2), height: Math.max(1, rect.height + pad*2), scale: 1 }; }
async function getLogos(cdp){ return evalValue(cdp,`Array.from(document.querySelectorAll('[aria-label="C4 Studios"]')).map((el, i) => { const r = el.getBoundingClientRect(); return { index:i, x:r.x, y:r.y, width:r.width, height:r.height, cx:r.x+r.width/2, cy:r.y+r.height/2, visible:r.width>0&&r.height>0 }; })`); }
async function mouseMove(cdp,x,y){ await cdp.send('Input.dispatchMouseEvent',{type:'mouseMoved',x,y,button:'none'}); }
async function click(cdp,x,y){ await cdp.send('Input.dispatchMouseEvent',{type:'mousePressed',x,y,button:'left',clickCount:1}); await cdp.send('Input.dispatchMouseEvent',{type:'mouseReleased',x,y,button:'left',clickCount:1}); }
async function sampleWord(cdp){ return evalValue(cdp,`(() => { const logo = document.querySelector('[aria-label="C4 Studios"]'); if (!logo) return null; const svg = logo.querySelector('svg'); const paths = Array.from(svg.querySelectorAll('path')); const letters = paths.slice(-7); return letters.map((el, index) => ({ index, dLength:(el.getAttribute('d')||'').length, transform:getComputedStyle(el).transform, opacity:getComputedStyle(el).opacity })); })()`); }
async function main(){ await fs.mkdir(outDir,{recursive:true}); const cdp=await connect(); await cdp.send('Page.navigate',{url:'http://127.0.0.1:4173/'}); await sleep(1800); await evalValue(cdp,`localStorage.setItem('c4_intro_seen', '1'); true`); await cdp.send('Page.reload',{ignoreCache:true}); await sleep(2200);
 const header=(await getLogos(cdp))[0]; const idleMetrics=await sampleWord(cdp); await captureClip(cdp,'header_idle',paddedClip(header)); await mouseMove(cdp,header.cx,header.cy); await sleep(250); await captureClip(cdp,'header_hover',paddedClip(header)); await click(cdp,header.cx,header.cy); await sleep(520); await captureClip(cdp,'header_build',paddedClip(header)); await sleep(820); await captureClip(cdp,'header_impact',paddedClip(header)); await sleep(1100); const lockMetrics=await sampleWord(cdp); await captureClip(cdp,'header_lock',paddedClip(header)); await click(cdp,header.cx,header.cy); await sleep(1150); const reverseMetrics=await sampleWord(cdp); await captureClip(cdp,'header_reverse',paddedClip(header));
 await evalValue(cdp,`(() => { const logos = document.querySelectorAll('[aria-label="C4 Studios"]'); logos[logos.length - 1]?.scrollIntoView({ block: 'center', inline: 'nearest' }); return true; })()`); await sleep(900); const footer=(await getLogos(cdp)).sort((a,b)=>b.y-a.y)[0]; await captureClip(cdp,'footer_idle',paddedClip(footer)); await mouseMove(cdp,footer.cx,footer.cy); await sleep(250); await captureClip(cdp,'footer_hover',paddedClip(footer)); await click(cdp,footer.cx,footer.cy); await sleep(520); await captureClip(cdp,'footer_build',paddedClip(footer)); await sleep(820); await captureClip(cdp,'footer_impact',paddedClip(footer)); await sleep(1100); await captureClip(cdp,'footer_lock',paddedClip(footer)); await click(cdp,footer.cx,footer.cy); await sleep(1150); await captureClip(cdp,'footer_reverse',paddedClip(footer));
 const report={ idleMetrics, lockMetrics, reverseMetrics, captures:['header_idle','header_hover','header_build','header_impact','header_lock','header_reverse','footer_idle','footer_hover','footer_build','footer_impact','footer_lock','footer_reverse'] }; await fs.writeFile(path.join(outDir,'runtime-audit.json'),JSON.stringify(report,null,2)); cdp.ws.close(); }
main().catch((error)=>{ console.error(error); process.exit(1); });
