/**
 * Case Study Data
 *
 * Each entry is keyed by its URL slug. Add new case studies by
 * adding a new key to CASE_STUDIES — no other files need to change.
 *
 * Screenshot / thumbnail placeholders:
 *   - Set `thumbnail` to '' to show a styled "Thumbnail pending" state
 *   - Set screenshot `url` to '' to show a numbered placeholder tile
 *   - Replace with real URLs when assets are ready
 */

export const CASE_STUDIES = {
  'transform-fremantle': {
    slug: 'transform-fremantle',
    name: 'Transform Fremantle',
    oneLiner: 'A purpose-built community platform uniting churches across Fremantle — designed to coordinate prayer, share resources, and grow a movement.',
    client: 'Transform Fremantle',
    location: 'Fremantle, WA',
    timeline: '3 weeks',
    budget: '$1k – $2.5k',
    role: 'Solo (design, development, deployment)',
    liveUrl: 'https://transformfreo.com/',
    year: '2026',
    category: 'web_design',
    tags: ['Website', 'Community', 'Non-Profit'],
    featured: true,
    budgetOrder: 2,

    cover: '/covers/transform-fremantle.png',
    brandColor: '#1e3a5f',
    thumbnail: '/captures/transformfreo-com/desktop/01-hero.png',

    overview: 'Transform Fremantle is an interdenominational Christian movement uniting churches across the City of Fremantle in coordinated prayer. They needed a digital home that could communicate vision, coordinate five weekly prayer meetings across different venues, host downloadable resources, and invite the community to connect — all while reflecting the warmth and gravity of the mission. The result is a clean, purposeful platform that treats the content with the seriousness it deserves while remaining approachable and easy to navigate.',

    screenshots: [
      { url: '/captures/transformfreo-com/desktop/01-hero.png', caption: 'Hero — harbour backdrop with mission statement and navigation' },
      { url: '/captures/transformfreo-com/desktop/02-schedule.png', caption: 'Prayer Meetings — five-day weekly schedule across Fremantle churches' },
      { url: '/captures/transformfreo-com/desktop/03-vision.png', caption: 'Vision & Aim — four numbered pillars of the movement' },
      { url: '/captures/transformfreo-com/desktop/04-connect.png', caption: 'Connect — contact form with validation and ways to reach us' },
      { url: '/captures/transformfreo-com/desktop/05-resources.png', caption: 'Resources — downloadable PDF library with branded cards' },
    ],

    desktopScreenshots: [
      { url: '/captures/transformfreo-com/desktop/01-hero.png', caption: 'Hero — harbour backdrop with mission statement and navigation' },
      { url: '/captures/transformfreo-com/desktop/02-schedule.png', caption: 'Prayer Meetings — five-day weekly schedule across Fremantle churches' },
      { url: '/captures/transformfreo-com/desktop/03-vision.png', caption: 'Vision & Aim — four numbered pillars of the movement' },
      { url: '/captures/transformfreo-com/desktop/04-connect.png', caption: 'Connect — contact form with validation and ways to reach us' },
      { url: '/captures/transformfreo-com/desktop/05-resources.png', caption: 'Resources — downloadable PDF library with branded cards' },
    ],

    mobileScreenshots: [
      { url: '/captures/transformfreo-com/mobile/01-hero.png', caption: 'Mobile — hero and mission introduction' },
      { url: '/captures/transformfreo-com/mobile/02-schedule.png', caption: 'Mobile — prayer meetings schedule' },
      { url: '/captures/transformfreo-com/mobile/03-vision.png', caption: 'Mobile — vision and aim pillars' },
      { url: '/captures/transformfreo-com/mobile/04-connect.png', caption: 'Mobile — contact form' },
      { url: '/captures/transformfreo-com/mobile/05-resources.png', caption: 'Mobile — resource library' },
    ],

    delivered: [
      'Logo design — anchor and compass-inspired mark in navy and gold, sized for web, social, and print',
      'Complete website — design, development, content structuring, and deployment',
      'Platform migration from Base44 scaffold to standalone Vite + Vercel architecture',
      'Homepage with hero, vision statement, and prayer meeting schedule',
      'Five-day prayer schedule with church names, addresses, times, and map links',
      'About page with mission statement and unity principles',
      'Vision & Aim page with four structured aims and supporting copy',
      'Statement of Faith page with formatted Apostles\' Creed',
      'Downloadable PDF resource library with automated build-time manifest',
      'Connect page with contact form, phone, Instagram, and bank transfer details',
      'Serverless contact form with email delivery, anti-spam, and rate limiting',
      'Responsive design optimised for mobile and desktop',
    ],

    features: [
      'Five-page SPA with branded hero sections and consistent layout system',
      'Weekly prayer schedule with five venues, times, and embedded map links',
      'Contact form with serverless email delivery via Vercel Functions and Resend',
      'Honeypot anti-spam and IP-based rate limiting on form submissions',
      'Automated PDF resource pipeline with SHA-256 cache busting and build-time verification',
      'Resource overrides system for managing display names and deprecation without code changes',
      'Vision & Aim page with numbered pillars and iconography',
      'Mobile-first responsive layout with sticky blurred header and hamburger navigation',
      'Smooth page transitions and micro-animations via Framer Motion',
      'Bank transfer details section for supporters',
    ],

    stack: [
      'React 18 (Vite SPA)',
      'JavaScript (JSX)',
      'Tailwind CSS 3.4 + shadcn/ui',
      'React Router DOM v7',
      'Framer Motion',
      'Lucide React',
      'Vercel Serverless Functions',
      'Resend (transactional email)',
      'Supabase Storage (image CDN)',
      'Vercel (hosting)',
    ],

    integrations: [
      'Serverless email delivery via Resend with formatted HTML templates',
      'Supabase Storage for image and PDF asset hosting',
      'Google Maps links for each prayer venue',
      'Instagram profile link for community engagement',
      'Honeypot anti-spam and IP-based rate limiting',
    ],

    performance: [
      'Semantic HTML with ARIA live regions and proper form labelling',
      'Responsive images with appropriate sizing',
      'Fast page loads via Vite code splitting and static asset optimisation',
      'Content-hash cache busting on PDF resources',
      'Clean URL structure with SPA fallback routing',
      'Mobile-optimised touch targets and typography',
      'Production safety guards blocking accidental localhost API calls',
    ],

    challenges: [
      'Migrating from a low-code platform (Base44/Supabase) to a production-ready standalone architecture',
      'Engineering a resource management system that lets non-technical users update PDFs without touching code',
      'Building a reliable serverless contact form with anti-spam, rate limiting, and proper email deliverability',
      'Coordinating content across five different churches with varying schedules',
      'Presenting theological content in a modern, readable format without losing gravity',
      'Balancing warmth and approachability with the seriousness of the mission',
    ],

    improvements: [
      'Add a headless CMS so the client can update prayer schedules and content independently',
      'Implement persistent rate limiting via Vercel KV or Upstash Redis',
      'Add privacy-respecting analytics to track page views and resource downloads',
      'Expand the resource library with categorised filtering',
    ],
  },

  'transform-hakea': {
    slug: 'transform-hakea',
    name: 'Transform Hakea',
    oneLiner: 'A polished, purpose-built website for a Christian prayer movement focused on the transformation of Hakea Prison, Perth.',
    client: 'Transform Hakea',
    location: 'Perth, WA',
    timeline: '',
    budget: '',
    role: 'Solo (design, development, deployment)',
    liveUrl: 'https://transformhakea.com',
    year: '',
    category: 'web_design',
    tags: ['Website', 'Community', 'Non-Profit'],
    featured: false,
    budgetOrder: 1,

    cover: '/covers/transform-hakea.png',
    brandColor: '#7a1a1a',
    thumbnail: '/captures/transformhakea-com/desktop/01-hero.png',

    overview: 'Transform Hakea is a single-page website built for a community of Christians who gather weekly to pray for the transformation of Hakea Prison in Western Australia. The site communicates the movement\'s vision, provides practical details about the weekly prayer gathering, and offers multiple ways to connect — all wrapped in a clean, branded design built for fast performance and search-engine readiness from day one.',

    screenshots: [
      { url: '/captures/transformhakea-com/desktop/01-hero.png', caption: 'Hero — slideshow with prison backdrop and dual call-to-action' },
      { url: '/captures/transformhakea-com/desktop/02-faq.png', caption: 'FAQ — practical questions for first-time visitors' },
      { url: '/captures/transformhakea-com/desktop/03-section.png', caption: 'Weekly Prayer Gathering — come and pray with us' },
      { url: '/captures/transformhakea-com/desktop/04-section.png', caption: 'Call to Action — Will You Pray With Us?' },
      { url: '/captures/transformhakea-com/desktop/05-section.png', caption: 'Partnership — Prison Fellowship Australia' },
    ],

    desktopScreenshots: [
      { url: '/captures/transformhakea-com/desktop/01-hero.png', caption: 'Hero — slideshow with prison backdrop and dual call-to-action' },
      { url: '/captures/transformhakea-com/desktop/02-faq.png', caption: 'FAQ — practical questions for first-time visitors' },
      { url: '/captures/transformhakea-com/desktop/03-section.png', caption: 'Weekly Prayer Gathering — come and pray with us' },
      { url: '/captures/transformhakea-com/desktop/04-section.png', caption: 'Call to Action — Will You Pray With Us?' },
      { url: '/captures/transformhakea-com/desktop/05-section.png', caption: 'Partnership — Prison Fellowship Australia' },
    ],

    mobileScreenshots: [
      { url: '/captures/transformhakea-com/mobile/01-hero.png', caption: 'Mobile — hero with slideshow' },
      { url: '/captures/transformhakea-com/mobile/02-faq.png', caption: 'Mobile — FAQ accordion' },
      { url: '/captures/transformhakea-com/mobile/03-section.png', caption: 'Mobile — Will You Pray With Us?' },
      { url: '/captures/transformhakea-com/mobile/04-section.png', caption: 'Mobile — come and pray with us' },
      { url: '/captures/transformhakea-com/mobile/05-section.png', caption: 'Mobile — Prison Fellowship Australia' },
    ],

    delivered: [
      'Logo design — crimson and copper emblem with cross motif, optimised for web and social use',
      'Full website — design, development, and deployment from scratch',
      'Custom brand colour system (crimson, maroon, copper palette)',
      'Responsive layout for mobile, tablet, and desktop',
      'Hero section with automatic image slideshow and cross-fade transitions',
      'Animated FAQ accordion with smooth expand/collapse',
      'Sticky navigation with scroll-aware active-section highlighting',
      'SEO configuration — meta tags, Open Graph, Twitter cards, structured data, sitemap, robots.txt',
      'Static export deployment pipeline for Cloudflare Pages',
      'Calendar .ics file download for recurring prayer gathering',
      'Google Maps integration for venue directions',
      'Custom 404 error page',
      'Iterative content updates across multiple client revision rounds',
    ],

    features: [
      'Hero image slideshow with cross-fade transitions, dot indicators, and reduced-motion support',
      'Sticky frosted-glass header with IntersectionObserver-driven section highlighting',
      'Animated FAQ accordion with chevron rotation and CSS grid expand/collapse',
      'One-click .ics calendar download for a recurring weekly event',
      'JSON-LD structured data for SEO (Organisation and FAQPage schemas)',
      'Dynamic sitemap and robots.txt generated via Next.js metadata routes',
      'Open Graph and Twitter Card metadata for full social sharing support',
      'Partnership section with Prison Fellowship Australia branding',
      'Cross-promotion with Transform Fremantle sister movement',
      'Custom branded 404 page',
    ],

    stack: [
      'Next.js 15 (App Router, static export)',
      'TypeScript (strict mode)',
      'Tailwind CSS 3 with custom design tokens',
      'Lucide React',
      'Cloudflare Pages (hosting)',
      'ESLint + Prettier',
    ],

    integrations: [
      'Google Maps — external directions link to Hakea Prison Visitor\'s Centre',
      'Calendar — client-side .ics file generation and download',
      'External links to Transform Fremantle and Prison Fellowship Australia',
      'Email (mailto) and phone (tel) contact links',
    ],

    performance: [
      'Fully static export with no server-side rendering dependency',
      'TypeScript strict mode with ESLint and Prettier enforcement',
      'Skip-to-content link, ARIA attributes, and focus-visible ring styles',
      'Prefers-reduced-motion handling for all animations',
      'Priority loading for above-fold hero images, lazy loading for the rest',
      'JSON-LD structured data, Open Graph, and Twitter Card metadata',
      'All images served locally — no external CDN dependency',
    ],

    challenges: [
      'Static-only deployment with no server-side capabilities — all interactivity built client-side',
      'Multiple rounds of client content revisions requiring clean Git workflow and rapid turnaround',
      'SEO groundwork for a brand-new domain with no existing authority',
      'Balancing a premium feel with a simple, accessible experience for a non-technical audience',
      'Cross-referencing the Transform Fremantle sister movement without creating confusion',
    ],

    improvements: [
      'Add a headless CMS so the client can update content without code commits',
      'Implement scroll-triggered entrance animations for section reveals',
      'Add privacy-respecting analytics to track visitor engagement',
    ],
  },

  'jurassic-pt': {
    slug: 'jurassic-pt',
    name: 'Jurassic PT',
    oneLiner: 'A conversion-focused service website for a Cannington fitness studio — covering memberships, classes, timetable, personal training, remedial massage, and direct booking.',
    client: 'Jurassic PT',
    location: 'Cannington, WA',
    timeline: '',
    budget: '',
    role: 'Solo (design, development, deployment)',
    liveUrl: 'https://www.jurassicpt.com/',
    year: '2026',
    category: 'web_design',
    tags: ['Website', 'Fitness', 'Local Business'],
    featured: true,
    budgetOrder: 3,

    cover: '/covers/jurassic-pt.png',
    brandColor: '#1a1f14',
    thumbnail: '/captures/jurassic-pt-vercel-app/desktop/01-hero.png',

    overview: 'Jurassic PT is a service website for a small group personal training studio in Cannington, WA offering coached classes, personal training, and remedial massage. The site is structured around practical customer actions — comparing memberships, checking the weekly timetable, booking sessions through PT Mate, or sending service-specific enquiries. Each service line has its own dedicated route with pricing, policies, and contextual calls-to-action that route into either direct booking flows or prefilled contact enquiries depending on availability. The implementation pairs a dark lime-accent visual system with reusable booking components, responsive layouts, and a lightweight trust layer built from real client testimonials.',

    screenshots: [
      { url: '/captures/jurassic-pt-vercel-app/desktop/01-hero.png', caption: 'Hero — headline, credentials, and dual CTA above the fold' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/02-section.png', caption: 'Why Jurassic PT — four value propositions in card layout' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/03-team.png', caption: 'Testimonials — community stories grid with expandable cards' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/04-memberships.png', caption: 'Memberships — dedicated pricing page with tiered plans and feature breakdown' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/05-memberships-plans.png', caption: 'Memberships — plan comparison cards with booking CTAs' },
    ],

    desktopScreenshots: [
      { url: '/captures/jurassic-pt-vercel-app/desktop/01-hero.png', caption: 'Hero — headline, credentials, and dual CTA above the fold' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/02-section.png', caption: 'Why Jurassic PT — four value propositions in card layout' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/03-team.png', caption: 'Testimonials — community stories grid with expandable cards' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/04-memberships.png', caption: 'Memberships — dedicated pricing page with tiered plans and feature breakdown' },
      { url: '/captures/jurassic-pt-vercel-app/desktop/05-memberships-plans.png', caption: 'Memberships — plan comparison cards with booking CTAs' },
    ],

    mobileScreenshots: [
      { url: '/captures/jurassic-pt-vercel-app/mobile/01-hero.png', caption: 'Mobile — hero with headline and booking CTAs' },
      { url: '/captures/jurassic-pt-vercel-app/mobile/02-hero-about.png', caption: 'Mobile — about section and value propositions' },
      { url: '/captures/jurassic-pt-vercel-app/mobile/03-memberships.png', caption: 'Mobile — memberships page hero and pricing overview' },
      { url: '/captures/jurassic-pt-vercel-app/mobile/04-memberships-plans.png', caption: 'Mobile — membership plan comparison cards' },
      { url: '/captures/jurassic-pt-vercel-app/mobile/05-classes.png', caption: 'Mobile — coached class descriptions and booking' },
    ],

    delivered: [
      'Logo design — badge-style brand mark with dinosaur claw motif, gold trim, and dark background treatment',
      'Multi-route marketing site with dedicated pages for classes, timetable, memberships, personal training, remedial massage, and contact',
      'PT Mate booking integration for memberships, intro offers, casual classes, and selected remedial massage services',
      'Fallback enquiry routing for services without direct booking links',
      'Contact form with client-side validation, loading states, and service-specific prefills via query parameters',
      'Membership comparison page with tiered plans, casual option, 10-class pack, FAQ, and policy detail',
      'Responsive timetable with both image-based schedule and structured weekly summary',
      'Custom testimonial system with scrolling ticker, expandable grid cards, and modal detail view',
      'Responsive navigation with desktop dropdown, mobile slide-in menu, and persistent membership CTA',
      'Route-level page titles and meta descriptions within the SPA shell',
      'Vercel deployment with SPA routing, CSP headers, HSTS, and cache configuration',
    ],

    features: [
      'Seven-route SPA with service-specific pages, CTAs, and booking flows',
      'PT Mate integration with centralised booking URL management and contextual fallback to contact enquiry',
      'Contact form with FormSubmit delivery, validation, consent capture, and query-parameter prefills from service pages',
      'Membership comparison with tiered pricing cards, highlighted plan, FAQ, and transparent cancellation policy',
      'Dual timetable display — image schedule and structured weekly summary with responsive card layout on mobile',
      'Testimonial ticker with continuous scroll, reduced-motion fallback, and expanded modal view',
      'IntersectionObserver-driven reveal animations with prefers-reduced-motion handling',
      'Centralised business configuration for booking URLs, contact details, and enquiry routing logic',
      'Sticky frosted-glass navigation with scroll-aware state and mobile hamburger menu',
      'Custom 404 page and scroll-to-top behaviour on route changes',
    ],

    stack: [
      'React 18 (Vite SPA)',
      'JavaScript (JSX)',
      'React Router DOM',
      'Tailwind CSS with custom design tokens',
      'Lucide React',
      'FormSubmit (contact form)',
      'PT Mate (booking integration)',
      'Vercel (hosting)',
    ],

    integrations: [
      'PT Mate — direct purchase links for memberships, intro offers, casual passes, and massage sessions',
      'FormSubmit — AJAX form submission for contact enquiries with success and error handling',
      'Google Maps — external directions link to the studio location',
      'Instagram and Facebook — social profile links for community engagement',
    ],

    performance: [
      'Lightweight production bundle via Vite with no heavy animation dependencies',
      'Lazy-loaded timetable image asset',
      'Skip-to-content link, ARIA labels, expanded states, and focus-visible styles',
      'Reduced-motion handling on all scroll-triggered animations',
      'Route-specific title and description updates for search engines',
      'Security headers including CSP, HSTS, and frame-ancestor restrictions',
      'Robots and sitemap configuration for deployment',
    ],

    challenges: [
      'Designing a clean booking architecture around mixed booking rules — some services route to PT Mate, others intentionally fall back to direct enquiry',
      'Building a content-heavy service site without a CMS while keeping pricing, policies, links, and contact pathways consistent across multiple pages',
      'Making the timetable useful on both desktop and mobile with a graceful switch from image schedule to structured card layout',
      'Adding social proof and motion without making the site feel noisy — including a continuously scrolling testimonial ticker with reduced-motion handling',
      'Creating clear route-by-route service discovery with page-specific CTAs and prefilled enquiry flows from each service page',
    ],

    improvements: [
      'Add a headless CMS so the client can update schedules, pricing, and testimonials independently',
      'Replace the image-based timetable with a fully data-driven schedule component',
      'Implement persistent rate limiting on form submissions',
      'Add privacy-respecting analytics to track page views and booking conversions',
    ],
  },

  'people-power': {
    slug: 'people-power',
    name: 'People Power',
    oneLiner: 'A C4 Studios Original — a full-stack social platform for creating, discovering, and coordinating community movements, built from the ground up with real-time messaging, moderation infrastructure, and governance tooling.',
    client: 'C4 Studios (Internal)',
    location: 'Perth, WA',
    timeline: '',
    budget: '',
    role: 'Solo (concept, design, logo, full-stack development, deployment)',
    liveUrl: 'https://peoplepower.app/',
    year: '2026',
    category: 'web_app',
    tags: ['Web App', 'Social Platform', 'C4 Original'],
    featured: true,
    budgetOrder: 5,

    cover: '/covers/people-power.png',
    brandColor: '#1a1d4d',
    thumbnail: '/captures/peoplepower-app/desktop/01-intro.png',

    overview: 'People Power is a full-stack social platform conceived, designed, and engineered entirely in-house at C4 Studios. It is not a client project — it is an original product built to enable communities to create, discover, and coordinate real social movements. The platform goes far beyond a typical feed: users can launch movement pages with evidence and claims, collaborate through tasks and discussions, organise events, run petitions, and engage with real-time messaging secured by end-to-end encryption scaffolding. Behind the public surface sits a complete operational layer — admin moderation workflows with second-approval governance, community health analytics, incident logging, feature flag administration, and safety-first reporting flows for both harmful content and product bugs. The backend is a production Fastify server backed by Postgres, with WebSocket support, rate limiting, CORS enforcement, and a Cloudflare Worker migration path already underway. This is not a marketing site or a prototype — it is a working social product with authentication, real-time state, and the kind of moderation infrastructure that most platforms only add after they have a problem.',

    screenshots: [
      { url: '/captures/peoplepower-app/desktop/01-intro.png', caption: 'Intro — cinematic brand overlay with mission statement and lightning-bolt mark' },
      { url: '/captures/peoplepower-app/desktop/02-feed.png', caption: 'Feed — movement discovery with sort modes and action panel' },
      { url: '/captures/peoplepower-app/desktop/03-feed-scroll.png', caption: 'Movement cards — tags, momentum indicators, and participation stats' },
      { url: '/captures/peoplepower-app/desktop/04-feed-impact.png', caption: 'Impact sort — movements ranked by community reach and engagement' },
      { url: '/captures/peoplepower-app/desktop/05-feed-impact-scroll.png', caption: 'Impact feed — movement cards with progress indicators and collaboration cues' },
    ],

    desktopScreenshots: [
      { url: '/captures/peoplepower-app/desktop/01-intro.png', caption: 'Intro — cinematic brand overlay with mission statement and lightning-bolt mark' },
      { url: '/captures/peoplepower-app/desktop/02-feed.png', caption: 'Feed — movement discovery with sort modes and action panel' },
      { url: '/captures/peoplepower-app/desktop/03-feed-scroll.png', caption: 'Movement cards — tags, momentum indicators, and participation stats' },
      { url: '/captures/peoplepower-app/desktop/04-feed-impact.png', caption: 'Impact sort — movements ranked by community reach and engagement' },
      { url: '/captures/peoplepower-app/desktop/05-feed-impact-scroll.png', caption: 'Impact feed — movement cards with progress indicators and collaboration cues' },
    ],

    mobileScreenshots: [
      { url: '/captures/peoplepower-app/mobile/01-intro.png', caption: 'Mobile — intro overlay with bold typography and gradient lighting' },
      { url: '/captures/peoplepower-app/mobile/02-feed.png', caption: 'Mobile — movement feed with sort tabs and stacked movement cards' },
      { url: '/captures/peoplepower-app/mobile/03-feed-scroll.png', caption: 'Mobile — feed scroll with movement cards and participation stats' },
      { url: '/captures/peoplepower-app/mobile/04-feed-impact.png', caption: 'Mobile — impact sort showing community-ranked movements' },
      { url: '/captures/peoplepower-app/mobile/05-feed-impact-scroll.png', caption: 'Mobile — impact feed with movement detail cards' },
    ],

    delivered: [
      'Logo design — lightning-bolt emblem with gradient treatment, sized for web, social, and favicon use',
      'Complete social platform — concept, UX, visual identity, front-end, back-end, and deployment',
      'Movement feed with momentum, newest, impact, and local discovery sort modes',
      'Full movement creation flow with categories, location, media upload, evidence fields, live preview, and anti-brigading checks',
      'Rich movement detail pages combining comments, collaboration tools, evidence, impact updates, resources, events, petitions, and polls',
      'Real-time messaging architecture with WebSocket support and end-to-end encryption key handling',
      'Search with movement and user discovery, city and country filtering, and profile-based location defaults',
      'Profile system with editable details, banner and avatar imagery, follower and following lists, trust markers, and movement history',
      'Full authentication flow — sign-in, sign-up, email verification, resend verification, password reset, and token refresh',
      'Reporting centre for abuse reports and technical bug reports with evidence upload and category-specific guidance',
      'Admin moderation workflow with reports queue, incident log, second-approval for permanent actions, and notification handling',
      'Community health dashboard with platform-level safety and moderation metrics over time',
      'Feature flag and research mode administration for controlled rollouts',
      'Safety and onboarding layers including intro gating, safety acceptance, age verification, and privacy-aware location handling',
      'Fastify backend with CORS, rate limiting, multipart uploads, health endpoints, WebSocket upgrades, and Postgres persistence',
      'Cloudflare Worker migration scaffold with Durable Objects entity CRUD',
    ],

    features: [
      'Movement feed with four discovery modes — momentum, newest, impact, and local — surfacing movement cards with tags, participation stats, and map previews',
      'Multi-step movement creation with media upload validation, profanity filtering, leadership-cap governance, platform acknowledgment gating, and rate-limiting hooks',
      'Movement detail pages that aggregate comments, collaborators, tasks, discussions, polls, events, petitions, resources, and impact updates in a single navigable surface',
      'Real-time messaging infrastructure with WebSocket transport, local fallback logic, and TweetNaCl-based end-to-end encryption key generation and shared-secret handling',
      'Reporting and moderation system with abuse and bug report modes, evidence upload, admin queue, second-approval governance for permanent actions, and incident logging',
      'Community health analytics dashboard with time-series moderation metrics and platform safety indicators',
      'Privacy-aware location system with approximate city-level map previews, sanitised public profile data, and geocoding only when explicitly needed',
      'Profile system with banner and avatar imagery, follower and following relationships, trust markers, and movement participation history',
      'Feature flag administration for staged rollouts and experimental features',
      'Cinematic intro overlay with animated gradient lighting, brand mark presentation, and mission-driven onboarding copy',
      'Graceful degradation across auth and backend availability states — offline labels, degraded sync banners, and stub fallbacks',
      'Lazy-loaded route-level code splitting with Vite manual chunk configuration for vendor groups',
    ],

    stack: [
      'React 18 (Vite 6 SPA)',
      'JavaScript (JSX)',
      'React Router 7',
      'Tailwind CSS + Radix UI + shadcn-style components',
      'TanStack React Query',
      'Framer Motion',
      'React Hook Form + Zod',
      'Leaflet + React Leaflet',
      'Recharts',
      'i18next',
      'Lucide React',
      'Fastify 5 (Node.js backend)',
      'Postgres (REAL mode persistence)',
      'Supabase Auth',
      'WebSockets (real-time messaging)',
      'TweetNaCl (E2E encryption)',
      'Cloudflare Pages + Workers (migration scaffold)',
      'Render (backend hosting)',
    ],

    integrations: [
      'Supabase Auth — email/password authentication with verification, session restoration, token refresh, and route-level protection',
      'Postgres — canonical data persistence in REAL mode with in-memory DEMO fallback for development',
      'WebSockets — real-time messaging transport with upgrade handling on the Fastify server',
      'TweetNaCl — end-to-end encryption keypair generation and shared-secret message encryption',
      'Resend / SMTP — non-blocking transactional email for verification and notifications',
      'Leaflet — privacy-aware map previews with approximate city-level coordinates',
      'Recharts — time-series analytics and community health metric visualisation',
      'Cloudflare Workers + Durable Objects — emerging migration layer for edge-deployed entity CRUD',
    ],

    performance: [
      'Route-level lazy loading with React.lazy and Suspense for code-split page bundles',
      'Vite manual chunk splitting separating React, Supabase, React Query, motion, forms, map, charting, and UI dependency groups',
      'TanStack React Query for server-state caching, background refetching, and optimistic updates',
      'Reduced-motion support implemented globally in CSS',
      'Graceful degradation with offline and degraded-state feedback across all authenticated surfaces',
      'Rate limiting on backend endpoints for submission and upload flows',
      'CORS enforcement, request body limits, and health status endpoints on the API server',
    ],

    challenges: [
      'Designing a movement coordination platform that handles activism-style organisation without becoming an unmoderated social feed — requiring substantial work around safety, reporting, appeal paths, and governance constraints',
      'Building a broad feature surface anchored on a single movement entity — combining comments, collaborators, tasks, evidence, events, petitions, resources, and impact updates in one coherent detail experience',
      'Implementing real-time messaging infrastructure with WebSocket transport and encryption key handling while keeping the platform functional when the backend is unavailable',
      'Balancing user empowerment with anti-abuse guardrails — leadership caps, anti-brigading checks, content controls, age verification, and second-approval governance for permanent moderation actions',
      'Managing authentication, profile persistence, and protected routing across frontend and backend concerns with email verification, password reset, and token-based API access',
      'Handling privacy-sensitive location features in a socially coordinated app — sanitising public profile data and using approximate city-level map presentation',
      'Supporting graceful degradation during an active backend migration across Node/Fastify, Render, and an emerging Cloudflare Worker layer',
      'Maintaining a consistent design language across public, authenticated, and admin surfaces without switching to unrelated visual systems',
    ],

    improvements: [
      'Complete the Cloudflare Worker migration for edge-deployed API endpoints',
      'Ship the full messaging UI with conversation threads and real-time delivery indicators',
      'Add server-side rendering or static generation for SEO on public movement pages',
      'Implement persistent rate limiting via Upstash Redis or Cloudflare KV',
      'Add privacy-respecting analytics to track platform engagement and movement growth',
    ],
  },
  'gocc': {
    slug: 'gocc',
    name: 'GoCC',
    oneLiner: 'Performance consultancy for a coaching and counselling practice — accelerating load times, smoothing interactions, and expanding reach through technical optimisation and SEO strategy.',
    client: 'GoCC — Coaching & Counselling',
    location: 'Success, WA',
    timeline: '2 weeks',
    budget: '$1k – $2.5k',
    role: 'Consultant (performance audit, optimisation, SEO strategy)',
    liveUrl: 'https://gocc.com.au/',
    year: '2026',
    category: 'brand_platform',
    tags: ['Consultancy', 'Optimisation', 'SEO'],
    featured: true,
    budgetOrder: 2,

    cover: null,
    brandColor: '#2a6e5a',
    thumbnail: '/captures/gocc-com-au/desktop/01-hero.png',

    overview: 'GoCC is a coaching and counselling practice based in Success, Western Australia, helping individuals and couples navigate relationships, career challenges, and personal growth. The existing website had solid content and a clear message — "Don\'t Just Survive, Thrive!" — but was underperforming technically: slow page loads, unoptimised assets, missing SEO fundamentals, and scroll-triggered animations that weren\'t debounced properly. C4 Studios was brought in to consult the developer directly — auditing the codebase, identifying bottlenecks, and guiding a series of targeted improvements that made the site faster, smoother, and more discoverable without a full rebuild.',

    screenshots: [
      { url: '/captures/gocc-com-au/desktop/01-hero.png', caption: 'Hero — full-width background with mission statement and booking CTA' },
      { url: '/captures/gocc-com-au/desktop/02-section.png', caption: 'Journey section — empathetic copy with lifestyle imagery and scroll reveal' },
      { url: '/captures/gocc-com-au/desktop/03-section.png', caption: 'Call to action — "Take the Chance to Change" with booking prompt' },
    ],

    desktopScreenshots: [
      { url: '/captures/gocc-com-au/desktop/01-hero.png', caption: 'Hero — full-width background with mission statement and booking CTA' },
      { url: '/captures/gocc-com-au/desktop/02-section.png', caption: 'Journey section — empathetic copy with lifestyle imagery and scroll reveal' },
      { url: '/captures/gocc-com-au/desktop/03-section.png', caption: 'Call to action — "Take the Chance to Change" with booking prompt' },
    ],

    mobileScreenshots: [
      { url: '/captures/gocc-com-au/mobile/01-hero.png', caption: 'Mobile — hero with condensed headline and booking button' },
      { url: '/captures/gocc-com-au/mobile/02-section.png', caption: 'Mobile — journey section with stacked layout' },
      { url: '/captures/gocc-com-au/mobile/03-section.png', caption: 'Mobile — call to action and booking prompt' },
    ],

    delivered: [
      'Comprehensive performance audit — Lighthouse profiling, asset analysis, render-blocking resource identification, and load waterfall review',
      'Image optimisation strategy — conversion to WebP, responsive srcset implementation, and lazy loading for below-fold assets',
      'Scroll animation refactor — debounced Intersection Observer callbacks replacing inefficient scroll listeners, with reduced-motion fallbacks',
      'CSS delivery optimisation — critical CSS extraction, deferred non-essential stylesheets, and removal of unused rules',
      'JavaScript bundle review — identified and eliminated render-blocking scripts, deferred third-party widget loading',
      'SEO foundation audit — meta tags, Open Graph markup, structured data (LocalBusiness schema), semantic heading hierarchy, and alt text review',
      'Local SEO recommendations — Google Business Profile optimisation guidance, NAP consistency check, and local keyword targeting',
      'Core Web Vitals improvements — LCP, FID, and CLS optimisation resulting in measurable score increases',
      'Caching strategy — recommended browser cache headers and CDN configuration for static assets',
      'Accessibility quick wins — colour contrast adjustments, focus-visible styles, and ARIA label additions on interactive elements',
    ],

    features: [
      'Full-page performance audit with before/after Lighthouse scoring',
      'Image pipeline overhaul — WebP conversion, responsive sizing, and lazy loading',
      'Scroll animation performance refactor with Intersection Observer and reduced-motion support',
      'SEO audit covering meta tags, structured data, heading hierarchy, and Open Graph',
      'Local SEO strategy including Google Business Profile and NAP consistency',
      'Core Web Vitals optimisation targeting LCP, FID, and CLS benchmarks',
      'Asset delivery improvements — critical CSS, deferred scripts, and cache headers',
      'Accessibility review with contrast, focus, and ARIA improvements',
    ],

    stack: [
      'HTML / CSS / JavaScript',
      'Intersection Observer API',
      'WebP image format',
      'Google Lighthouse',
      'Google Search Console',
      'Acuity Scheduling (booking)',
    ],

    integrations: [
      'Acuity Scheduling — embedded booking widget for session appointments',
      'Google Business Profile — local SEO presence and review management',
      'Google Search Console — indexing status and search performance monitoring',
    ],

    performance: [
      'Lighthouse performance score improved from mid-60s to 90+ on mobile',
      'Largest Contentful Paint reduced by optimising hero background image delivery',
      'Cumulative Layout Shift eliminated through explicit image dimensions and font-display swap',
      'First Input Delay improved by deferring non-critical JavaScript and debouncing scroll handlers',
      'Total page weight reduced through image compression, unused CSS removal, and script consolidation',
      'Time to Interactive improved with render-blocking resource elimination',
    ],

    challenges: [
      'Consulting an external developer rather than having direct codebase access — all changes were guided through recommendations and code review',
      'Improving performance without altering the site\'s visual design or content structure',
      'Balancing aggressive optimisation with the developer\'s existing architecture and deployment constraints',
      'Addressing SEO fundamentals on a site that had no prior technical SEO work',
      'Communicating technical improvements in terms the business owner could understand and approve',
    ],

    improvements: [
      'Implement server-side rendering or static generation for faster initial paint',
      'Add structured data for FAQ and service pages',
      'Set up automated Lighthouse CI checks for ongoing performance monitoring',
      'Expand content strategy with blog posts targeting local counselling search queries',
    ],
  },

  'groverz-tax': {
    slug: 'groverz-tax',
    name: 'Groverz Tax & Accounting Solutions',
    oneLiner: 'A conversion-focused tax practice website with an interactive refund estimator and physics-driven hero animations.',
    client: 'Ankit Grover',
    location: 'East Cannington, Perth, WA, Australia',
    timeline: '2–3 weeks',
    budget: '$2.5k – $5k',
    role: 'Solo (design, development, deployment)',
    liveUrl: 'https://groverztax.com.au',
    year: '2026',
    category: 'web_design',
    tags: ['Website', 'Tax & Accounting', 'Small Business', 'Local Service'],
    featured: true,
    budgetOrder: 4,

    cover: '/covers/groverz-tax.png',
    brandColor: '#1e1b4b',
    thumbnail: '/captures/groverztax-com-au/desktop/01-hero.png',

    overview: 'Ankit Grover needed a professional web presence that matched the quality of his independent tax practice in East Cannington, Perth. C4 Studios designed and built a four-page React SPA with a clear conversion funnel — from an interactive tax refund estimator using live ATO tax brackets, through a seven-service accordion catalogue with category filtering, to a backend-powered contact form with rate limiting, honeypot spam protection, and Resend email delivery. Hero sections feature a custom canvas-based physics simulation of drifting tax symbols, and the navigation uses a liquid-glass hover effect built with Framer Motion. The result is a polished, mobile-first site that positions Groverz as the approachable, no-nonsense alternative to big-box accounting firms.',

    screenshots: [
      { url: '/captures/groverztax-com-au/desktop/01-hero.png', caption: 'Hero — floating math symbol physics simulation with social proof and wave divider' },
      { url: '/captures/groverztax-com-au/desktop/02-benefits.png', caption: 'Trust markers — Registered Tax Agent, fixed fees, fast turnaround, and document checklist' },
      { url: '/captures/groverztax-com-au/desktop/03-testimonials.png', caption: 'Client testimonials with star ratings, avatar initials, and attribution' },
      { url: '/captures/groverztax-com-au/desktop/04-calculator.png', caption: 'Interactive tax refund estimator using 2025-26 ATO resident rates' },
      { url: '/captures/groverztax-com-au/desktop/05-services.png', caption: 'Seven-service card grid with hover accents and red reveal bar' },
      { url: '/captures/groverztax-com-au/desktop/06-cta.png', caption: 'Full-width CTA section with C4 Studios credit badge' },
    ],

    desktopScreenshots: [
      { url: '/captures/groverztax-com-au/desktop/01-hero.png', caption: 'Hero — floating math symbol physics simulation with social proof and wave divider' },
      { url: '/captures/groverztax-com-au/desktop/02-benefits.png', caption: 'Trust markers — Registered Tax Agent, fixed fees, fast turnaround, and document checklist' },
      { url: '/captures/groverztax-com-au/desktop/03-testimonials.png', caption: 'Client testimonials with star ratings, avatar initials, and attribution' },
      { url: '/captures/groverztax-com-au/desktop/04-calculator.png', caption: 'Interactive tax refund estimator using 2025-26 ATO resident rates' },
      { url: '/captures/groverztax-com-au/desktop/05-services.png', caption: 'Seven-service card grid with hover accents and red reveal bar' },
      { url: '/captures/groverztax-com-au/desktop/06-cta.png', caption: 'Full-width CTA section with C4 Studios credit badge' },
    ],

    mobileScreenshots: [
      { url: '/captures/groverztax-com-au/mobile/01-hero.png', caption: 'Mobile — hero with responsive typography and stacked CTA' },
      { url: '/captures/groverztax-com-au/mobile/02-calculator.png', caption: 'Mobile — tax refund estimator form stacked vertically' },
      { url: '/captures/groverztax-com-au/mobile/03-benefits.png', caption: 'Mobile — trust markers and checklist in single-column layout' },
      { url: '/captures/groverztax-com-au/mobile/04-testimonials.png', caption: 'Mobile — client testimonial cards' },
      { url: '/captures/groverztax-com-au/mobile/05-cta.png', caption: 'Mobile — CTA section with stacked buttons' },
      { url: '/captures/groverztax-com-au/mobile/06-services.png', caption: 'Mobile — service cards in single-column layout' },
    ],

    delivered: [
      'Complete website — design, development and deployment (React SPA on Vercel)',
      'Homepage with hero, stats bar, service grid, trust markers, document checklist, tax estimator, testimonials, and CTA',
      'About page with founder profile card, service overview, expectations grid, process timeline, and FAQ',
      'Services page with seven-service filterable accordion catalogue, client type grid, pricing section, process timeline, tax estimator, and FAQ',
      'Contact page with multi-field enquiry form, Google Maps embed, phone/email cards, and office info sidebar',
      'Custom 404 page with branded styling and navigation recovery links',
      'Interactive tax refund estimator calculator using 2025-26 ATO resident tax rates',
      'Contact form backend with Resend email integration, rate limiting, honeypot anti-spam, input sanitisation, and styled HTML emails',
      'Vercel serverless API route for contact form (with legacy Netlify Functions support)',
      'Responsive design — fully mobile-first from 320px to ultrawide',
      'Floating WhatsApp chat button linked to business number',
      'Google Maps embed for office location',
      'Security headers (CSP, X-Frame-Options, Referrer-Policy, Permissions-Policy)',
      'SEO meta tags (title, description, theme-color, lang="en-AU")',
      'C4 Studios credit badge with GSAP-animated SVG wordmark in footer and CTA sections',
      'Content writing and copywriting for all pages',
    ],

    features: [
      'Interactive tax refund estimator using 2025-26 ATO resident tax rates with real-time calculation',
      'Seven-service accordion system with category filtering (Personal, Business, Trusts & Companies, Finance) and Framer Motion animation',
      'Canvas-based floating math symbol physics simulation with elastic collisions, wall bouncing, and seeded randomness',
      'Liquid-glass hover effect on desktop navigation with radial gradient, backdrop blur, and spring physics',
      'Testimonial cards with five-star ratings, avatar initials, and decorative serif quotation marks',
      'Four-step visual process timeline with alternating layout and connecting gradient line',
      'Sticky header with backdrop blur, mobile hamburger navigation, and body scroll lock',
      'Document checklist section with two-column icon grid layout for appointment preparation',
      'Stats bar — Over 5000 returns, $99 individual, 5★ Google reviews, 100% ATO compliant',
      'ATO late-lodgement penalty warning banner with click-to-open info modal',
      'Contact form with honeypot anti-spam, server-side rate limiting, input sanitisation, and field-level validation',
      'Styled HTML email templates sent via Resend with branded navy header and Perth timezone formatting',
      'C4 Studios credit badge featuring GSAP morphing SVG wordmark with dormant/mono/colour state transitions',
      'Floating WhatsApp button with WhatsApp Business deep link',
      'Google Maps embed (sandboxed, lazy-loaded) with office address card',
      'Acknowledgement of Country for the Whadjuk people of the Noongar nation in footer',
      'prefers-reduced-motion respected — canvas animation disabled entirely for accessibility',
    ],

    stack: [
      'React 18.2 (Vite SPA)',
      'JavaScript (JSX)',
      'Vite 6.1',
      'React Router DOM 6.26',
      'Tailwind CSS 3.4 + shadcn/ui (Radix primitives)',
      'Framer Motion 11.16',
      'GSAP 3.14 + @gsap/react 2.1',
      'Lucide React 0.475',
      'Resend 6.10 (transactional email)',
      'PostCSS + Autoprefixer',
      'ESLint 9.x + Prettier 3.8',
      'Vercel (hosting + serverless functions)',
    ],

    integrations: [
      'Resend — transactional email for contact form submissions with styled HTML templates',
      'Google Maps Embed API — office location on contact page (sandboxed iframe, lazy-loaded)',
      'WhatsApp Business — floating chat button deep-linking to business number',
      'Vercel Serverless Functions — /api/contact POST endpoint for form processing',
      'Netlify Functions — legacy contact route via redirect',
    ],

    performance: [
      'Security headers: X-Content-Type-Options, X-Frame-Options, Referrer-Policy, Permissions-Policy, CSP',
      'SEO: descriptive <title> with location + price, <meta description>, theme-color, lang="en-AU"',
      'Canvas animation respects prefers-reduced-motion — completely disabled for accessibility',
      'Canvas particle count halved on mobile viewports for GPU performance',
      'Google Maps iframe uses loading="lazy" and sandbox attributes for security and deferred load',
      'Vite code splitting and tree shaking for minimal bundle size',
      'Input sanitisation (NFKC normalisation, control char stripping, length limits) prevents injection',
      'Rate limiting on contact API (5 requests per 15-minute window per IP)',
      'Semantic HTML with proper heading hierarchy, nav, main, footer landmarks',
      'ARIA attributes on icon buttons, mobile menu toggle, form states',
      'Keyboard-accessible accordion and select via Radix UI primitives',
    ],

    challenges: [
      'Building a canvas-based floating symbol system with elastic collision physics that felt organic without being distracting — required seeded randomness, spin-transfer on collision, and angular velocity damping',
      'Designing a service accordion that scales across four categories with filtering, animated expand/collapse, and included-items checklists without layout shift',
      'Creating a tax refund estimator using real ATO brackets while clearly labelling it as an estimate — required careful disclaimer placement and bracket-accurate edge-case handling',
      'Implementing a contact form backend that works identically across Vercel serverless, Netlify Functions, and Vite dev middleware — solved with a shared service module and adapter layers',
      'Achieving a liquid-glass hover effect on desktop navigation that feels responsive and physical — solved with spring physics, getBoundingClientRect tracking, and layered radial gradients with backdrop blur',
    ],

    improvements: [
      'Add Open Graph and Twitter Card meta tags for social sharing previews',
      'Implement page-level code splitting with React.lazy() and Suspense to reduce initial bundle',
      'Add a sitemap.xml and robots.txt for improved search engine crawling',
      'Replace photo placeholder with actual professional photography of Ankit and the office',
      'Add analytics (Google Analytics or Plausible) for visitor tracking and contact form conversion',
    ],
  },

  'ds-racing-karts': {
    slug: 'ds-racing-karts',
    name: 'DS Racing Karts',
    oneLiner: 'Full e-commerce platform with 499+ go kart parts, Square payment integration, and a custom-built Canvas 2D racing mini-game.',
    client: 'Dion Scott / DS Racing Karts',
    location: 'Long Reef Crescent, Woodbine, NSW, Australia',
    timeline: 'Approx. 3–4 months (late 2025 – early 2026)',
    budget: '$10k+',
    role: 'Solo — design, development, deployment, backend migration, analytics setup, copywriting, SEO, error tracking',
    liveUrl: 'https://www.dsracingkarts.com.au/',
    year: '2025–2026',
    category: 'ecommerce',
    tags: ['E-Commerce', 'Web Application', 'Square Integration', 'Go Karting', 'Motorsport', 'Product Catalogue', 'Game Design'],
    featured: true,
    budgetOrder: 10,

    cover: '/covers/ds-racing-karts.png',
    brandColor: '#ffffff',
    thumbnail: '/captures/dsracingkarts-com-au/desktop/01-hero.png',

    overview: `DS Racing Karts is a comprehensive e-commerce platform built for one of Sydney's most experienced kart specialists — Dion Scott, a racer and engineer with nearly 40 years in the sport. The client needed a complete digital storefront to sell go kart parts, showcase services, and represent the brand online. C4 Studios delivered a full-stack e-commerce solution featuring 499+ products migrated from Square's catalogue via a custom 4-stage data pipeline (CSV import → category deduplication → image migration via Square Catalog API → AI-powered description generation with Claude Haiku). The platform includes a custom-built 'DSR Grand Prix' slot-car racing mini-game (2,291 lines of hand-written Canvas 2D code), GSAP ScrollTrigger-powered 3D scroll animations throughout, a full admin dashboard with CRUD product management, Sentry error tracking across three runtimes, and comprehensive security hardening including HSTS, CSP, rate limiting, and HMAC-SHA256 webhook verification. This is the largest and most technically ambitious project in the C4 Studios portfolio.`,

    screenshots: [
      { url: '/captures/dsracingkarts-com-au/desktop/01-hero.png', caption: 'Homepage hero — "BUILT FOR SPEED. ENGINEERED TO WIN." with autoplay video and cycling background images' },
      { url: '/captures/dsracingkarts-com-au/desktop/02-trust-banner.png', caption: 'Trust banner — Race-Ready Parts, Expert Service, Australia-Wide shipping' },
      { url: '/captures/dsracingkarts-com-au/desktop/03-game-teaser.png', caption: 'DSR Grand Prix mini-game teaser with "PRESS START" CTA' },
      { url: '/captures/dsracingkarts-com-au/desktop/04-game-racing.png', caption: 'DSR Grand Prix in action — two karts racing head-to-head on The Circuit' },
      { url: '/captures/dsracingkarts-com-au/desktop/05-categories.png', caption: 'Shop by Category grid with custom hand-drawn SVG icons' },
      { url: '/captures/dsracingkarts-com-au/desktop/06-history.png', caption: 'History timeline — scroll-driven trunk growth with alternating cards and lightbox images' },
      { url: '/captures/dsracingkarts-com-au/desktop/07-speedometer.png', caption: 'RPM tachometer stats counter — 500+ Parts, 40 Years, 1000+ Karts with redline bounce' },
      { url: '/captures/dsracingkarts-com-au/desktop/08-race-animation.png', caption: 'Scroll-pinned SVG race animation — two detailed top-down karts with exhaust glow' },
      { url: '/captures/dsracingkarts-com-au/desktop/09-latest-products.png', caption: 'Latest Products carousel with live pricing from Supabase' },
      { url: '/captures/dsracingkarts-com-au/desktop/10-newsletter.png', caption: '"Stay in the Fast Lane" newsletter signup with chequered background' },
      { url: '/captures/dsracingkarts-com-au/desktop/11-shop.png', caption: 'Shop page — 499+ products with category sidebar, sort, pagination, and search' },
      { url: '/captures/dsracingkarts-com-au/desktop/12-product.png', caption: 'Product detail page with image gallery, SKU, pricing, stock status, and add-to-cart' },
      { url: '/captures/dsracingkarts-com-au/desktop/13-cart.png', caption: 'Shopping cart with quantity controls, GST calculation, and checkout CTA' },
      { url: '/captures/dsracingkarts-com-au/desktop/14-checkout.png', caption: 'Checkout — customer details, shipping address, Square Web Payments card form' },
      { url: '/captures/dsracingkarts-com-au/desktop/15-confirmation.png', caption: 'Order confirmation — DSR-XXXXX number with 3-step "What happens next" guide' },
      { url: '/captures/dsracingkarts-com-au/desktop/16-services.png', caption: 'Services page — 7 expandable service cards with included-items checklists' },
      { url: '/captures/dsracingkarts-com-au/desktop/17-workshop.png', caption: '"Built for Performance" workshop showcase with cut-corner image' },
      { url: '/captures/dsracingkarts-com-au/desktop/18-racewear.png', caption: 'Custom racewear gallery — 12 product photos in responsive grid' },
      { url: '/captures/dsracingkarts-com-au/desktop/19-about-founder.png', caption: 'Dion Scott founder profile with photo, blockquote bio, and career highlights' },
      { url: '/captures/dsracingkarts-com-au/desktop/20-teams.png', caption: 'Racing teams carousel — 9 team profiles with numbers, logos, and accent colours' },
      { url: '/captures/dsracingkarts-com-au/desktop/21-results.png', caption: 'Results timeline — 2024 ERC Podiums, 2023 Endurance Victories, 2021 SEK Wins' },
      { url: '/captures/dsracingkarts-com-au/desktop/22-chassis.png', caption: '"Know Your Chassis" — Sprint, Endurance, and DSR Predator technical breakdowns' },
      { url: '/captures/dsracingkarts-com-au/desktop/23-sponsors.png', caption: 'Sponsor carousel — 19+ logos in infinite CSS scroll with gradient fade edges' },
      { url: '/captures/dsracingkarts-com-au/desktop/24-contact.png', caption: 'Contact page with DSR-branded form, location info, and appointment-only notice' },
      { url: '/captures/dsracingkarts-com-au/desktop/25-search.png', caption: 'Search autocomplete with Ctrl+K hotkey, rich results with images and categories' },
      { url: '/captures/dsracingkarts-com-au/desktop/26-scroll-video.png', caption: '3D perspective video container with scroll-driven rotation and red radial glow' },
      { url: '/captures/dsracingkarts-com-au/desktop/27-admin-dashboard.png', caption: 'Admin dashboard — product/order/customer counts, recent orders, low stock alerts' },
      { url: '/captures/dsracingkarts-com-au/desktop/28-admin-products.png', caption: 'Admin product management — search, status filter, stock colour coding, pagination' },
      { url: '/captures/dsracingkarts-com-au/desktop/29-admin-editor.png', caption: 'Admin product editor — images, variations, inventory, categories, SEO fields' },
      { url: '/captures/dsracingkarts-com-au/desktop/30-404.png', caption: 'Custom 404 page — giant "404" with racing-themed CTAs' },
    ],

    desktopScreenshots: [
      { url: '/captures/dsracingkarts-com-au/desktop/01-hero.png', caption: 'Homepage hero with video and headline' },
      { url: '/captures/dsracingkarts-com-au/desktop/04-game-racing.png', caption: 'DSR Grand Prix mini-game mid-race' },
      { url: '/captures/dsracingkarts-com-au/desktop/05-categories.png', caption: 'Shop by Category grid' },
      { url: '/captures/dsracingkarts-com-au/desktop/07-speedometer.png', caption: 'RPM tachometer stats counter' },
      { url: '/captures/dsracingkarts-com-au/desktop/08-race-animation.png', caption: 'Scroll-pinned SVG race animation' },
      { url: '/captures/dsracingkarts-com-au/desktop/09-latest-products.png', caption: 'Latest Products carousel' },
      { url: '/captures/dsracingkarts-com-au/desktop/11-shop.png', caption: 'Shop page with filters and products' },
      { url: '/captures/dsracingkarts-com-au/desktop/12-product.png', caption: 'Product detail page' },
      { url: '/captures/dsracingkarts-com-au/desktop/13-cart.png', caption: 'Shopping cart' },
      { url: '/captures/dsracingkarts-com-au/desktop/14-checkout.png', caption: 'Checkout with Square payment' },
      { url: '/captures/dsracingkarts-com-au/desktop/16-services.png', caption: 'Services page with expandable cards' },
      { url: '/captures/dsracingkarts-com-au/desktop/19-about-founder.png', caption: 'Founder profile — Dion Scott' },
      { url: '/captures/dsracingkarts-com-au/desktop/20-teams.png', caption: 'Racing teams carousel' },
      { url: '/captures/dsracingkarts-com-au/desktop/23-sponsors.png', caption: 'Sponsor logo carousel' },
      { url: '/captures/dsracingkarts-com-au/desktop/24-contact.png', caption: 'Contact page with form' },
      { url: '/captures/dsracingkarts-com-au/desktop/27-admin-dashboard.png', caption: 'Admin dashboard' },
      { url: '/captures/dsracingkarts-com-au/desktop/29-admin-editor.png', caption: 'Admin product editor' },
    ],

    mobileScreenshots: [
      { url: '/captures/dsracingkarts-com-au/mobile/01-hero.png', caption: 'Mobile homepage hero' },
      { url: '/captures/dsracingkarts-com-au/mobile/02-game.png', caption: 'Mobile game with touch controls' },
      { url: '/captures/dsracingkarts-com-au/mobile/03-shop.png', caption: 'Mobile shop with product grid' },
      { url: '/captures/dsracingkarts-com-au/mobile/04-product.png', caption: 'Mobile product detail' },
      { url: '/captures/dsracingkarts-com-au/mobile/05-cart.png', caption: 'Mobile cart' },
      { url: '/captures/dsracingkarts-com-au/mobile/06-checkout.png', caption: 'Mobile checkout' },
      { url: '/captures/dsracingkarts-com-au/mobile/07-nav.png', caption: 'Mobile navigation with cart badge' },
      { url: '/captures/dsracingkarts-com-au/mobile/08-services.png', caption: 'Mobile services page' },
      { url: '/captures/dsracingkarts-com-au/mobile/09-contact.png', caption: 'Mobile contact form' },
    ],

    delivered: [
      'Complete e-commerce website — full design, development, and deployment',
      'Square payment integration with PCI-compliant card tokenisation and server-side payment processing',
      '4-stage data migration pipeline — Square CSV → Supabase import (2-pass category/product) → category deduplication → image migration (Square Catalog API → Supabase Storage) → AI description generation',
      'Product catalogue system with 499+ go kart parts synced from Square',
      'Individual product pages with image gallery, SKUs, pricing, stock status indicators, breadcrumb navigation, and Product structured data schema',
      'Shopping cart with add/remove/quantity management, GST calculation, and localStorage persistence',
      'Custom checkout flow with Square Web Payments SDK, customer details, shipping address with Australian state dropdown',
      'Order confirmation system with auto-incrementing DSR-XXXXX numbers and branded Resend confirmation emails',
      'Category-based product filtering with hierarchical sidebar navigation (parent > child)',
      'Product search with PostgreSQL trigram matching (pg_trgm), autocomplete overlay with Ctrl+K hotkey, and rich results',
      'Product pagination (24 per page) with ellipsis and prev/next controls',
      'Sort functionality (newest, price ascending/descending, name A-Z)',
      '7 detailed service pages — Kart Servicing, Engine Tuning, Chassis Setup, Engine Servicing, Race Preparation, Driver Coaching, Custom Racewear — each with included-items checklists and contextual enquiry CTAs',
      'Custom "DSR Grand Prix" slot-car racing mini-game — 2,291 lines of hand-written Canvas 2D code with physics engine, AI opponent, 4 tracks, F1-style countdown, and mobile touch controls',
      'GSAP ScrollTrigger-powered 3D scroll animations — history timeline, RPM tachometer, SVG race animation, 3D video container',
      'RPM tachometer-style animated statistics counter (500+ Parts, 40 Years, 1000+ Karts) with redline rev-limiter bounce',
      'Scroll-pinned SVG race animation — two detailed top-down karts with exhaust glow, kerbs, and finish-line flash',
      'Founder biography page with professional photo, racing history narrative, and career highlights',
      'Racing teams showcase with 9 team profiles (numbers 338, 43, 114, 5, 555, 272, 285, 22, 249) in modal carousel with swipe navigation',
      'Results/achievements timeline (2024 ERC Podiums, 2023 Endurance Victories, 2021 SEK Wins)',
      '"Know Your Chassis" educational content — Sprint, Endurance, and DSR Predator technical breakdowns',
      'Sponsor showcase with 19+ brand logos in dual-direction infinite CSS scroll carousel',
      'Contact form with dynamic subject prefills from service page CTAs, input validation, and HTML-escaped Resend email delivery',
      'Newsletter subscription system ("Stay in the Fast Lane") — Supabase upsert + optional Mailchimp double opt-in sync',
      'Cookie consent banner with Accept/Decline — localStorage persistence, GA4 conditionally loaded only on consent',
      'Google Analytics 4 integration with cookie-consent-gated loading',
      'Privacy Policy page (9 sections, Australian Privacy Principles compliant)',
      'Terms & Conditions page (10 sections, e-commerce focused)',
      'Custom racewear photo gallery with 12 product images in responsive grid with hover zoom',
      '"Built for Performance" workshop showcase section with cut-corner image design',
      'Responsive design (mobile + tablet + desktop) with mobile navigation overlay and body scroll lock',
      'Full SEO setup — per-page metadata, dynamic OG/Twitter/Apple icon generation (Edge runtime), sitemap.xml with all product slugs, robots.txt, LocalBusiness + Product structured data schemas',
      'AI-generated product descriptions — Claude Haiku 4.5 filled ~400 empty descriptions with dry-run mode and cost tracking',
      'Full admin dashboard with product/order/customer counts, recent orders table, and colour-coded low stock alerts',
      'Admin product editor — full CRUD for products including image upload/delete/set primary, variations, inventory, categories, SEO fields',
      'Admin category management with hierarchical table (parent bold, child indented with └) and product counts',
      'Admin customer list with search across name/email and pagination',
      'Admin order management with status badges, customer join, and pagination',
      'Supabase Auth with role-based admin access (admin/super_admin) and middleware redirect for unauthenticated requests',
      '12 custom hand-drawn SVG category icons — steering wheel, chain links, brake disc, axle, stub axle, ball bearing, helmet, chequered grid, fuel can, wrench, tie rod, car silhouette',
      'Hero video section with autoplay detection, 12-second fallback timeout, and crossfade to cycling background images',
      '3D perspective video container with scroll-driven rotation, red radial glow, and scanline overlay',
      'Sentry error tracking across client (10% traces, 100% error replays), server, and edge runtimes with global error boundary',
      'Security hardening — HSTS (2-year max-age + preload), CSP, X-Frame-Options DENY, X-Content-Type-Options nosniff, Permissions-Policy, rate limiting on all public API routes, HMAC-SHA256 webhook verification',
      'Square webhook handler for real-time order status updates (payment.updated → paid/cancelled)',
      'Lenis smooth scrolling (1.2s duration, exponential easing, 2× touch multiplier)',
      'PWA-ready web app manifest with standalone display mode and #e60012 theme colour',
      'Appointment-only modal popup system for workshop address clicks',
      'C4 Studios credit badge in header and footer with animated wordmark',
      'All page content writing and copywriting',
      'Loading skeleton states for shop page, product page, and admin products page',
      'Custom 404 page with racing-themed CTAs',
      'Search autocomplete overlay with keyboard navigation (↑/↓/Enter/Escape), Ctrl+K global hotkey, debounced API calls',
    ],

    features: [
      'Full e-commerce platform with 499+ go kart parts, synced from Square\'s product catalogue via a 4-stage migration pipeline',
      'Custom-built "DSR Grand Prix" slot-car racing mini-game — 2,291 lines of Canvas 2D code with curvature-based physics, 4-tier AI difficulty, 4 tracks including a "Campbelltown GP" local Easter egg, F1-style 5-light countdown with false start detection, persistent skid marks, and mobile touch controls',
      'Square payment integration — client-side PCI-compliant card tokenisation via Web Payments SDK, server-side createPayment() with idempotency keys and BigInt AUD amounts',
      'GSAP 3.14 + ScrollTrigger-powered 3D scroll animations — history timeline with SVG trunk growth, RPM tachometer with rev-limiter bounce, scroll-pinned SVG kart race, 3D perspective video container',
      'Animated RPM tachometer stats counter — realistic SVG face (0–16,000 RPM), scroll-driven needle with sinusoidal rev-limiter oscillation at redline, gold-to-red arc gradient, 3 counter-up stat cards',
      'Dynamic product catalogue with hierarchical category sidebar, stock filtering, sort (newest/price/name), 24-per-page pagination with ellipsis, and PostgreSQL trigram search',
      'Product detail pages with multi-image gallery, SKU display, variation selection, sale pricing, stock status indicators, breadcrumb navigation, sanitised HTML descriptions, and Product structured data (AggregateOffer)',
      'Shopping cart with React Context + localStorage persistence, quantity controls, line item management, GST (10%) calculation, and "Estimated Total" display',
      'Custom checkout flow — Square Web Payments SDK dynamically loaded, card tokenise → server price validation against DB → Square payment → Supabase order with auto-increment DSR-XXXXX → inventory decrement → Resend branded confirmation email',
      '7-service showcase with expandable accordion cards, Lucide icon mapping, "What\'s Included" checklists (6 items each), and contextual "Enquire Now" CTAs that pre-fill the contact form subject',
      'Founder biography section — Dion Scott profile with 3:4 aspect portrait, racing-red corner accent, blockquote narrative spanning 1989 to present, career credits including Fastrack Experiences V8 coaching',
      'Racing teams grid — 9 teams (numbers 338, 43, 114, 5, 555, 272, 285, 22, 249) in full-screen modal carousel with decorative SVG patterns (CheckeredCorner, TireTrack, SpeedLines), keyboard/swipe/dot navigation',
      'Results timeline — chronological achievement display (2024 ERC Podiums, 2023 Endurance Victories, 2021 SEK Wins) with red left-border accent and Orbitron digital year labels',
      '"Know Your Chassis" educational content — technical breakdowns of Sprint (7 specifications), Endurance, and DSR Predator chassis types with specifications grid',
      'Custom racewear gallery — 12 product photos in responsive 2/3/4-column grid with hover-zoom transform and gradient overlay',
      'Sponsor showcase with 19+ partner logos in dual-direction infinite CSS scroll (35s linear, 3× duplication), gradient fade edges, and hover image-swap (700ms crossfade)',
      'Newsletter subscription system ("Stay in the Fast Lane") — POST to /api/newsletter → Supabase upsert + optional Mailchimp REST API sync with double opt-in (status: "pending"), rate limited 5/15min',
      'Cookie consent banner (custom, no external library) — Accept/Decline stored in localStorage as "dsr-cookie-consent", GA4 script tag conditionally rendered only when consent granted',
      'Google Analytics 4 — loaded via next/script afterInteractive strategy, zero Google scripts until explicit cookie Accept',
      'Contact form with dynamic subject pre-fills from service page CTAs (/contact?subject=Kart+Servicing), HTML-escaped output, Resend delivery to dsracing@bigpond.com, rate limited 3/15min',
      'Appointment-only modal system — triggered from Footer address click, "private residential property" warning, Contact Us / Got It action buttons, backdrop blur dismiss',
      '"Shop by Category" homepage grid with custom SVG category icons linking to filtered shop views',
      'Latest Products carousel on homepage — 8 newest products with live pricing from Supabase, priority image loading for first 4',
      'History timeline section — 9 nodes with GSAP scroll-driven SVG trunk line growth, alternating left/right cards with fade-in/out on scroll, terminal dot with pulse animation, fullscreen image lightbox with Escape key dismiss',
      'Mobile-responsive hamburger navigation with slide-down overlay, body scroll lock, and cart icon with product count badge',
      'C4 Studios animated credit badge — GSAP wordmark animation in header and footer',
      'Facebook social integration link',
      'Email link integration (info@dsracingkarts.com.au)',
      'Supabase Storage for product image hosting with Next.js Image optimisation (AVIF/WebP, 30-day edge cache)',
      'Admin dashboard — 5 parallel Supabase queries fetching product count, order count, customer count, recent 5 orders, and low stock items (≤3 quantity). Colour-coded stock thresholds (red ≤0, yellow ≤5, green >5)',
      'Admin product editor — full CRUD: name, description (HTML), SKU, status (active/draft/archived), visibility (visible/hidden/unavailable), variation management (name/SKU/price/sale price/stock qty), image upload to Supabase Storage with set-primary/delete, category tag selection, SEO title/description fields',
      'Supabase Auth with role-based access — email/password sign-in, admin_profiles table with admin/super_admin roles, middleware redirect for unauthenticated admin requests, API route-level auth checks',
      '4-stage data migration pipeline — (1) import-square-csv.js: 2-pass CSV import (Pass 1: categories with dedup, Pass 2: products/variations/inventory), (2) merge-categories.cjs: cleanup duplicate categories, (3) migrate-images.js: Square Catalog API download → Supabase Storage upload, (4) generate-descriptions.cjs: Claude Haiku for ~400 products with dry-run mode and backup JSON',
      'Sentry error tracking — client (10% traces, 100% error replays), server, and edge runtimes; error.tsx captures exceptions via Sentry.captureException; global-error.tsx as root boundary fallback',
      'Security hardening — HSTS max-age=63072000 (2 years) with includeSubDomains + preload, Content-Security-Policy with script/style/img/connect/frame source whitelisting, X-Frame-Options DENY, X-Content-Type-Options nosniff, Referrer-Policy strict-origin-when-cross-origin, Permissions-Policy camera=()/microphone=()/geolocation=()',
      'Rate limiting on all public API routes — checkout (10 requests/5min), contact (3/15min), newsletter (5/15min) — in-memory Map with timestamp expiry',
      'Square webhook handler — payment.updated events with fail-closed HMAC-SHA256 signature verification using crypto.timingSafeEqual, maps COMPLETED→paid / FAILED→pending / CANCELLED→cancelled',
      'Lenis smooth scrolling wrapping entire application — duration 1.2s, easing function (1 - Math.pow(2, -10 * t)), touchMultiplier 2×, rAF loop with cleanup on unmount',
      'PWA-ready manifest — standalone display, #e60012 theme_color, #0a0a0a background_color',
      'Scroll-pinned SVG race animation — 300vh pin, two DetailedKart SVG components (body with shading, 4 wheels with tread, helmet with visor, number circle, animated exhaust glow), full track with grass/kerbs/asphalt/finish lines, Kart 1 surge at 75%, drift at 90%, finish flash at 98%',
      '12 custom hand-drawn SVG category icons — SteeringWheelIcon, ChainIcon, BrakeDiscIcon, AxleIcon, StubAxleIcon, BearingIcon, HelmetIcon, ChequeredIcon, FuelCanIcon, WrenchIcon, TieRodIcon, CarIcon — all built as React components with SVG path data',
      'Hero video section — autoplay detection with canPlayThrough event, 12-second fallback timeout, crossfade to 4 cycling background images at 5-second intervals, DSR logo image, dual CTA buttons, animated scroll indicator with bounce',
      '3D perspective video container — IntersectionObserver auto-play/pause, scroll-driven transforms (rotateX 0→-8°→0°, rotateY sinusoidal ±3°, scale 0.92→1.03→0.97, translateY -20→0→-10px), perspective: 1200px, red radial glow with sinusoidal intensity, "racing monitor" frame with accent corners and scanline overlay',
      'Dynamic SEO image generation — opengraph-image, twitter-image, icon (32×32 "DSR" in red), apple-icon (180×180) — all Edge runtime ImageResponse',
      'Dynamic sitemap.xml — fetches all active products from Supabase, outputs static pages + all product slug URLs + category URLs',
      'Search autocomplete overlay — Ctrl+K / Cmd+K global hotkey, 300ms debounced API calls, keyboard navigation (↑/↓/Enter/Escape), rich results with product images + category badges + prices, "No results" state',
      'Loading skeleton states — animated pulse placeholders for shop page, product page, and admin products page matching actual layout structure',
      'Product image gallery — thumbnail strip navigation, primary image display with Next.js Image optimization',
      'LocalBusiness structured data on homepage, Product (AggregateOffer) structured data on product pages',
    ],

    stack: [
      'Next.js 14 (App Router)',
      'React 18',
      'TypeScript 5.7',
      'Tailwind CSS 3.4',
      'GSAP 3.14 + ScrollTrigger',
      '@gsap/react 2.1',
      'Lenis 1.3 (smooth scrolling)',
      'Square SDK 38.0 (Payments API — server-side)',
      'Square Web Payments SDK (client-side card tokenisation)',
      'Supabase JS 2.47 + SSR 0.5 (Postgres, Auth, Storage)',
      'PostgreSQL via Supabase (pg_trgm + uuid-ossp extensions)',
      'Resend 6.11 (transactional email)',
      'Sentry 10.49 (client, server, edge error tracking)',
      'Google Analytics 4 (cookie-consent-gated)',
      'Mailchimp REST API (newsletter sync, optional double opt-in)',
      'Canvas 2D API (custom game engine — zero external libraries)',
      'Lucide React 0.460 (icon library)',
      'clsx 2.1 + tailwind-merge 2.6 (class utilities)',
      'sanitize-html 2.17 (HTML sanitisation for product descriptions)',
      'Anthropic Claude Haiku 4.5 (build-time product description generation)',
      'csv-parse 5.6 (CSV processing for data migration)',
      'dotenv 16.4 (environment variable management)',
      'PostCSS 8.4 + Autoprefixer 10.4',
      'Node.js 22+',
      'Vercel (hosting)',
    ],

    integrations: [
      'Square Payments API — server-side paymentsApi.createPayment() in /api/checkout with card tokenisation, idempotency UUID, BigInt AUD amounts, buyer email, location ID',
      'Square Web Payments SDK — dynamically loaded client-side script, card.attach() to DOM ref, card.tokenize() for PCI-compliant card data, production/sandbox environment switching',
      'Square Catalog API — used in scripts/migrate-images.js to fetch all ITEM + IMAGE catalog objects for downloading and re-uploading product photos to Supabase Storage',
      'Square Webhooks — inbound payment.updated events at /api/webhooks/square, HMAC-SHA256 signature verification (notification URL + body hashed with webhook secret, timing-safe comparison), maps COMPLETED/FAILED/CANCELLED to Supabase order status',
      'Supabase Postgres — 12 tables, 15+ indexes (GIN tsvector + trigram for search), 19 RLS policies, GENERATED ALWAYS stock_status column, auto-incrementing DSR-XXXXX order numbers via PostgreSQL sequence + trigger, decrement_inventory() SECURITY DEFINER function',
      'Supabase Auth — email/password for admin panel, role-based access via admin_profiles table (admin/super_admin), middleware session refresh on every request, middleware redirect for unauthenticated admin requests',
      'Supabase Storage — product-images bucket, file upload from admin panel, public URLs served through Next.js Image with AVIF/WebP optimization and 30-day edge cache',
      'Resend — transactional email: (1) order confirmation emails with branded HTML template (racing red accents, item table, pricing breakdown), from orders@dsracingkarts.com.au; (2) contact form submissions from noreply@dsracingkarts.com.au to dsracing@bigpond.com with reply-to sender',
      'Google Analytics 4 — loaded via next/script afterInteractive only after cookie consent granted, measurement ID from NEXT_PUBLIC_GA_MEASUREMENT_ID env var, zero scripts loaded on decline',
      'Mailchimp REST API — optional newsletter sync from /api/newsletter, extracts datacenter from API key, POST to /lists/{id}/members with status "pending" (double opt-in), graceful fallback if keys not configured',
      'Anthropic Claude API — Haiku 4.5 used in scripts/generate-descriptions.cjs for build-time product description generation (~400 products), dry-run mode for testing, backup JSON export, cost tracking per request',
      'Sentry — @sentry/nextjs 10.49, configured across client (10% tracesSampleRate, 0% session replays, 100% error replays), server (10% traces), and edge (10% traces) runtimes, source maps uploaded with hideSourceMaps: true',
      'Facebook — social media link to @dsracingkarts page from footer and contact page',
      'Next.js Image CDN — remote patterns for Supabase Storage (*.supabase.co) and Square S3 CDN, AVIF/WebP format support, 30-day minimumCacheTTL, custom deviceSizes and imageSizes',
    ],

    performance: [
      'Next.js Image component used throughout with AVIF/WebP formats, custom deviceSizes (640–1920), and 30-day edge cache TTL',
      'Google Fonts loaded with display: swap for FOUT prevention — Oswald (headings), Inter (body), Orbitron (digital/stats)',
      'Game loaded via next/dynamic with ssr: false — zero SSR cost, code-split, lazy-loaded on demand from GameTeaser',
      'Game state managed via useRef (not useState) in rAF loop to avoid React re-renders during gameplay',
      'Scenery generation uses seeded random (sin hash) for deterministic caching across frames',
      'Skid marks capped at 300 with batch purge of 50 to prevent memory accumulation',
      'Product pagination (24/page) prevents loading all 499+ products at once',
      'Loading skeleton states for shop, product, and admin pages to prevent CLS',
      'Supabase queries use select with specific columns (no SELECT *) for minimal payload',
      'Admin dashboard runs 5 parallel Supabase queries via Promise.all for fast dashboard load',
      'CSS infinite scroll animations use will-change: transform for GPU acceleration',
      'Lenis smooth scrolling with requestAnimationFrame loop and cleanup on unmount',
      'Sentry configured with 10% trace sampling to minimise performance overhead',
      'Sentry source maps hidden from users (hideSourceMaps: true)',
      'IntersectionObserver for video auto-play/pause to avoid unnecessary media decoding',
      'Dynamic imports for Square Web Payments SDK — only loaded on checkout page',
      'Product images served through Next.js Image optimization pipeline: Supabase Storage → CDN → client with responsive srcset',
    ],

    challenges: [
      'Square catalogue migration — Building a 4-stage data pipeline to import 499+ products with categories, variations, pricing, inventory, and images from Square\'s CSV export format, handling escaped commas, "Name (SQUARE_ID)" notation, and "Parent > Child" category nesting',
      'E-commerce architecture without a platform — Constructing a complete shop experience (browse, filter, search, cart, checkout, payment, order management) on Next.js + Supabase without Shopify/WooCommerce, requiring custom cart context, price validation, inventory management, and order tracking',
      'Mini-game development in production — Designing and building a 2,291-line Canvas 2D racing game with physics, AI, and multiple tracks that runs smoothly alongside a content-heavy e-commerce site, using useRef patterns to avoid React re-render overhead in the animation loop',
      '3D scroll animation performance — Orchestrating multiple simultaneous GSAP ScrollTrigger instances (history timeline, tachometer, race animation, video container) on a homepage that also loads product images and embeds a game, requiring careful GPU acceleration and intersection-observer gating',
      'Product image pipeline — Migrating hundreds of product images from Square\'s S3-hosted catalogue (via Catalog API) to Supabase Storage, then serving through Next.js Image with AVIF/WebP optimization and 30-day CDN caching',
      'PCI-compliant payment flow — Implementing Square\'s client-side card tokenisation + server-side payment processing with idempotency keys, BigInt currency handling, fail-closed webhook verification (HMAC-SHA256 with timing-safe comparison), and graceful order status management on payment failure',
      'AI description generation at scale — Using Claude Haiku to generate meaningful descriptions for ~400 products that had empty or minimal descriptions, with dry-run mode, backup JSON, cost tracking, and preservation of existing specification content',
      'Security hardening across the stack — Implementing comprehensive security headers (HSTS, CSP, X-Frame-Options), rate limiting on all public API endpoints, HTML sanitisation for user-generated content, input sanitisation for search queries, and role-based admin access with middleware protection',
    ],

    improvements: [
      'Live inventory sync — Replace the current CSV-based import with Square\'s real-time inventory webhooks to keep stock levels automatically synchronised between Square POS and the website',
      'Product reviews and ratings — Add a customer review system with star ratings, moderation queue, and review-driven sort/filter to build social proof and improve product page SEO with Review structured data',
      'Related products and cross-selling — Implement "Customers also bought" and "You may also like" sections on product pages using category-based or purchase-history recommendations',
      'Shipping calculator — Integrate a shipping rate API (Australia Post, Sendle) to provide real-time shipping quotes at checkout instead of the current "quoted separately" approach',
      'Order tracking dashboard — Build a customer-facing order tracking page where buyers can check order status, view shipping updates, and access their order history without needing to contact support',
    ],
  },
};

export function getCaseStudy(slug) {
  return CASE_STUDIES[slug] || null;
}

export function getAllCaseStudies() {
  return Object.values(CASE_STUDIES);
}